environment:
  CONAN_RUN_TESTS: True
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PATH: C:\\Python37;C:\\Python37\Scripts;%PATH%
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

install:
  - python --version
  - python -m pip install conan --upgrade --user
  - python -m conans.conan user

build_script:
  - python -m conans.conan create .
